services:
  change_bot:
    build: .
    container_name: change_bot
    # Если бот упадет с ошибкой, Docker сам его перезапустит
    restart: always
    # Передаем секреты внутрь контейнера
    env_file:
      - .env
    # Ограничиваем ресурсы, чтобы бот не съел всю память сервера (для твоей Free Tier VM)
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
